// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbxI1fbFqFnp2r8sN0wUFyHuCAfw190W8',
    appId: '1:505705960497:web:4070236c64f7b3275ef110',
    messagingSenderId: '505705960497',
    projectId: 'school-bf32a',
    authDomain: 'school-bf32a.firebaseapp.com',
    storageBucket: 'school-bf32a.firebasestorage.app',
    measurementId: 'G-Z81QJLPKGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwJRFGBIxBMdBk2EHG0mvIHMn_j3WERjA',
    appId: '1:505705960497:android:6aefb75e24fc607e5ef110',
    messagingSenderId: '505705960497',
    projectId: 'school-bf32a',
    storageBucket: 'school-bf32a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC-i92EiBLy-hk5Innt_klXm-DqFsEjNg',
    appId: '1:505705960497:ios:c0c80872e905e54d5ef110',
    messagingSenderId: '505705960497',
    projectId: 'school-bf32a',
    storageBucket: 'school-bf32a.firebasestorage.app',
    iosBundleId: 'com.example.schoolPdf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC-i92EiBLy-hk5Innt_klXm-DqFsEjNg',
    appId: '1:505705960497:ios:c0c80872e905e54d5ef110',
    messagingSenderId: '505705960497',
    projectId: 'school-bf32a',
    storageBucket: 'school-bf32a.firebasestorage.app',
    iosBundleId: 'com.example.schoolPdf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbxI1fbFqFnp2r8sN0wUFyHuCAfw190W8',
    appId: '1:505705960497:web:52ab1b131f8cfde55ef110',
    messagingSenderId: '505705960497',
    projectId: 'school-bf32a',
    authDomain: 'school-bf32a.firebaseapp.com',
    storageBucket: 'school-bf32a.firebasestorage.app',
    measurementId: 'G-VD6LEM8DPZ',
  );
}
